repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
    - id: check-builtin-literals
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    - id: mypy
-   repo: https://gitlab.com/PyCQA/flake8
    rev: ''
    hooks:
    - id: flake8
-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: ''
    hooks:
    - id: check-poetry
