repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
    - id: check-builtin-literals
    - id: check-toml
    - id: flake8
    - id: debug-statements
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
